### ISSUE TITLE
本地测试结果与公布数据差距很大,

### ISSUE THREAD

**Issue by ghost** [smallnest/go-web-framework-benchmark#11]
测试环境
 go1.7 最新 beego ->default路径无返回值
硬件:
40  Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
Mem:      32765096
测试结果:
[root@test08 wrk]# ./wrk -t10 -c5000 -d60s http://127.0.0.1:8080/
Running 1m test @ http://127.0.0.1:8080/
  10 threads and 5000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   402.30ms  565.62ms   2.00s    81.05%
    Req/Sec     0.86k   639.03    13.29k    78.62%
  476512 requests in 1.00m, 70.44MB read
  Socket errors: connect 0, read 0, write 0, timeout 40477
Requests/sec:   7932.59
Transfer/sec:      1.17MB

Requests/sec 远远低于您第一项测试中0ms 100ms 等测试项的公布值, 不知道问题出在哪里.

**Comment by smallnest** [comment]
服务器一共多少个核?
你的业务代码是什么？看你的latency非常高

**Comment by ghost** [comment]
model name  : Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
cpu MHz     : 2299.952
cache size  : 25600 KB
cpu cores   : 10

全新空的 beego,  http://127.0.0.1:8080/路径下 没有任何计算量

**Comment by smallnest** [comment]
检查你的网络配置和 open files配置。
这个吞吐率Transfer/sec: 1.17MB 明显有问题
