### ISSUE TITLE
Last results 

### ISSUE THREAD

**Issue by ghost** [smallnest/go-web-framework-benchmark#12]

**Comment by smallnest** [comment]
Yes, I notices that.
I found Iris allocates more than fasthttp-raw so it is slower than fasthttp-raw. Hope this could help you.

**Comment by kataras** [comment]
I already told you that, but gas faster and fasthttp-routing faster than Iris..? I'm running the new benchmarks (with the change I did to the Iris) I will post new results...

**Comment by kataras** [comment]
Ok so far (with the test I'm running my own docker) we have iris alloc  = 48, gas alloc  = 49, fasthttp alloc = 33 (as before)

**Comment by kataras** [comment]
Ok so far (with the test I'm running my own docker) we have iris alloc  = 48, gas alloc  = 49, fasthttp alloc = 33 (as before)  so Iris is faster than gas if allocs are the only matters on benchmarks*?

**Comment by kataras** [comment]
Ok so far (with the test I'm running my own docker) we have iris alloc  = 48, gas alloc  = 49, fasthttp alloc = 33 (as before)  so Iris is faster than gas if allocs are the only matters on benchmarks*? Please re-run the benchmarks in your own docker which is faster ofcourse, when ever you have time, you have nothing to lose I think
