### ISSUE TITLE
issue in benchmark result for go-zero

### ISSUE THREAD

**Issue by dennissetiawan** [smallnest/go-web-framework-benchmark#138]
Hello , so i was trying to do benchmark for go-zero framework and got some weird result for the benchmark. Can you help to see wether or not something is wrong in the implementation?

Here are the implementation:
https://github.com/dennissetiawan/go-web-framework-benchmark

You can see the result in benchmark_trial_1/ and benchmark_trial_2/ folder

**Comment by vuhoanghiep1993** [comment]
did the go-zero benchmark result added? I also wating for it, thanks

**Comment by dennissetiawan** [comment]
[benchmark_result_gozero](https://github.com/dennissetiawan/go-web-framework-benchmark/tree/master/benchmark_result_gozero)

updated here

**Comment by dennissetiawan** [comment]
i solved the issue with disabling the default middlewares (check commit in my repo)

**Comment by vuhoanghiep1993** [comment]
Thank you for your support but when I compare your result and smallnest result, it not same, may be because of different envirorment when testing, 
But with benchmark, I think same enviroment is very important,

**Comment by dennissetiawan** [comment]
yes that's true, my test do not aim to compare it with smallnest's results. We want to compare go-zero with several other frameworks with the expectation in our local environment only with the expectation that if go zero is faster in one environment it would be faster also in another environment also
