### ISSUE TITLE
What do the processing time data infers?

### ISSUE THREAD

**Issue by stella551** [smallnest/go-web-framework-benchmark#148]
Hey, i was going through the docs and i was trying to infer what do the following csv infers to?
I tried looking for docs but didn't find any.

Any help would be appreciated.

https://github.com/smallnest/go-web-framework-benchmark/blob/master/testresults/processtime.csv

Thanks

**Comment by smallnest** [comment]
<img width="1058" alt="image" src="https://github.com/smallnest/go-web-framework-benchmark/assets/865763/fc6cb9cf-4ebc-481b-895e-3baafabf0b78">

`0ms`、`10ms`、`100ms`、`500ms` mean handler's process time:
https://github.com/smallnest/go-web-framework-benchmark/blob/master/server.go#L284
```go
time.Sleep(sleepTimeDuration)
```

`94880.07`、`81303.37` means each webframework's Throughput (requests/ second) at sleepTimeDuration==0
