### ISSUE TITLE
Remove some projects from benchmarks

### ISSUE THREAD

**Issue by flrdv** [smallnest/go-web-framework-benchmark#150]
`test.sh` for only 2 frameworks already runs for about 11–13 minutes, the whole test-suit is going to be lasting for many and many more hours. However, we can optimize this by getting rid of some abandoned projects. I've checked some, so here's my report:
`echo-slim`: repository is deleted
`fastrouter`: abandoned, latest commit was 7 years ago
`gojsonrest`: abandoned
`gongular`: abandoned, no PRs are reviewed since 2017
`gowww`: author had big plans, however latest commit was 4 years ago. The package by itself has no tests
`martini`: unmaintained, stated in the README
`neo`: seems abandoned, all the issues for the past 2–3 years has no answers
`traffic`: unmaintained, as stated in Bio.

You can check each of the above by yourself. As we come to the consensus, I can open a PR.

**Comment by smallnest** [comment]
please open a PR, thanks
