### ISSUE TITLE
Are frameworks with version below 1.0.0 forbidden?

### ISSUE THREAD

**Issue by flrdv** [smallnest/go-web-framework-benchmark#152]
In README is stated: __Only test those webframeworks which are stable.__ However, there is still a clevergo with version 0.6.0 and a couple more without any explicit version at all.

I would like to add own framework to comparisons (powered by own http engine, so in local runs it visibly outperforms fasthttp). It's covered by tests (unlike some already-added projects), I've got own website powered by it for a while, yet the version is still under 1.0.0 (semver is used for versioning). How acceptable would it be?

Just in case, [link](https://github.com/indigo-web/indigo)

**Comment by smallnest** [comment]
no. web frameworks below 1.0.0 don't means unstable. In many cases, it depends on the author's style

**Comment by flrdv** [comment]
> no. web frameworks below 1.0.0 don't means unstable. In many cases, it depends on the author's style

So, it's acceptable to make a PR, that would add my framework to benchmarks? Hopefully, it won't become obsoleted and "latest commit 7 years ago" in near future:)

**Comment by smallnest** [comment]
welcome
