### ISSUE TITLE
add latency and memory usage data in test result

### ISSUE THREAD

**Issue by smallnest** [smallnest/go-web-framework-benchmark#3]
Latency and memory usage are also important measures to compare go web frameworks.

**Comment by smallnest** [comment]
added

**Comment by smallnest** [comment]
@valyala

**Comment by valyala** [comment]
@smallnest , I'd recommend reducing the number of threads in `wrk` (`-t` argument) to the number of CPU cores in the system the wrk is running on or even to smaller values. This should reduce latencies unrelated to server implementations. See https://www.reddit.com/r/golang/comments/4ep79n/performance_test_java_undertow_go_fasthttp_and_go/d264856 for details.

**Comment by smallnest** [comment]
@valyala yes, I will change the scripts

**Comment by smallnest** [comment]
@valyala yes, I will change the scripts
