### ISSUE TITLE
New Benchmark?

### ISSUE THREAD

**Issue by Dexus** [smallnest/go-web-framework-benchmark#36]
Hello can you please provide a new benschmark? I can't get in to run on my Alpine Linux Server... because no wrk on ARM available...

Thank you!

**Comment by rebootcode** [comment]
+1 
There are other new frameworks added too like go-siris and no benchmarks results are available yet.

**Comment by smallnest** [comment]
yes, I will do next test but currently I need a available server for this test. When I find a  available server I will update test results.

**Comment by rebootcode** [comment]
@smallnest - what is server requirement - does it require more than 4GB ?

**Comment by smallnest** [comment]
I test it on a  32-cores server. See the README

**Comment by kirillDanshin** [comment]
just got runned it on my server, results and server hardware description below. can't wait for the official results :)

![benchmark](https://user-images.githubusercontent.com/9026581/28999911-23484790-7a63-11e7-9919-1fb4c08dc02e.png)

Intel Xeon E3-1231v3
32Gb RAM
2*2tb SATA (SATA6) in RAID1
`Linux ams-1 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127300
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 127300
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

[sysctl -a](https://gist.github.com/kirillDanshin/1c826eed130b15d493917a8596fb5a4f)

**Comment by kirillDanshin** [comment]
forgot to run pipelines, so here are all results:

**UPD**: upload right images

![concurrency_latency](https://user-images.githubusercontent.com/9026581/29004155-e69a8b64-7acb-11e7-966d-8095056307ce.png)
![concurrency-pipeline](https://user-images.githubusercontent.com/9026581/29004158-e69cd978-7acb-11e7-94de-9012c02ae731.png)
![concurrency](https://user-images.githubusercontent.com/9026581/29004156-e69af072-7acb-11e7-9a56-ab90315d59c7.png)
![concurrency_alloc](https://user-images.githubusercontent.com/9026581/29004159-e69d17f8-7acb-11e7-8faf-68f956950ade.png)
![benchmark](https://user-images.githubusercontent.com/9026581/29004160-e69de07a-7acb-11e7-8713-4cd1f2932ae2.png)
![benchmark_latency](https://user-images.githubusercontent.com/9026581/29004157-e69c6f06-7acb-11e7-9379-5094e811695d.png)
![benchmark-pipeline](https://user-images.githubusercontent.com/9026581/29004161-e6b4d14a-7acb-11e7-8e45-10e1b0325f76.png)
![benchmark_alloc](https://user-images.githubusercontent.com/9026581/29004162-e6b637a6-7acb-11e7-92aa-df776318bf20.png)

**Comment by kirillDanshin** [comment]
@smallnest friendly ping
when you plan to run the test? do I have time to release next Gramework version? I need about a week.

**Comment by smallnest** [comment]
yes,you can.
if you do the test after you release next gamework version,you can summit a PR, i can use your test result in readme. thanks

**Comment by kirillDanshin** [comment]
@smallnest cool, thank you for your trust.
but I think that results that I'll submit may be perceived as not objective because of good results of the gramework. maybe I'll give you a server for tests if I'll have a new one.

**Comment by smallnest** [comment]
updated test result
