### ISSUE TITLE
docker image not creating images with labels

### ISSUE THREAD

**Issue by nbari** [smallnest/go-web-framework-benchmark#38]
Hi, first at all, many thanks for sharing this project, has helped me to improve and detect some issues within my code and therefore learn more about how to profile/test in general.

Currently, I am giving a try to the docker  image but is not creating the images by just running this:

    docker run  -v /opt/data:/data smallnest/go-web-framework-benchmark

What I am doing to try to generate them, is to execute the `plot.sh`  something like:

    docker run -v /tmp/data:/data -t -i --entrypoint /bin/bash smallnest/go-web-framework-benchmark

then within the container, I run:

    docker-test.sh

When finished I run `plot.sh` within the `testresults`  this creates the images but without  labels, an example of the output:

![benchmark_alloc](https://user-images.githubusercontent.com/364199/30780292-f0a55820-a107-11e7-961a-cb5cd930d5d9.png)

Any idea of how to fix this? and if is not too much asking in the meantime could the benchmark results be updated?

thanks in advance.

**Comment by smallnest** [comment]
I have any idea about it, no fonts installed in the docker image?

**Comment by nbari** [comment]
Hi @smallnest I don't really know I am just using the image from the  README (https://hub.docker.com/r/smallnest/go-web-framework-benchmark/), probably needs to be updated, including the Dockerfile, it is working from your side?

**Comment by smallnest** [comment]
I will try it and maybe add fonts into docker image. Thanks.

**Comment by nbari** [comment]
@smallnest  I think is missing a call to the `plot.sh` in the  docker-test file: https://github.com/smallnest/go-web-framework-benchmark/blob/master/docker-test.sh#L10

seems that it only copies the existing images but not creating new ones.

**Comment by smallnest** [comment]
fixed. thanks

**Comment by nbari** [comment]
I gave a try but seems that the [fresh](https://github.com/smallnest/go-web-framework-benchmark/blob/master/server.go#L400)  config/setup is broken:

  ```
  Step 4/7 : RUN go get github.com/smallnest/go-web-framework-benchmark && mkdir /data
 ---> Running in 824e5a22021b
# github.com/smallnest/go-web-framework-benchmark
src/github.com/smallnest/go-web-framework-benchmark/server.go:400:12: f.Config().SetPort undefined (type fresh.Config has no field or method SetPort)
The command '/bin/sh -c go get github.com/smallnest/go-web-framework-benchmark && mkdir /data' returned a non-zero code: 2

```

**Comment by smallnest** [comment]
fixed. Fresh broken its API

**Comment by nbari** [comment]
From a fresh setup now I get this errors.

```
WARNING: Ignoring https://pkgs.alpinelinux.org/packages/x86_64/APKINDEX.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libressl2.6-libcrypto-2.6.3-r0:
    masked in: @main
    satisfies: wrk-4.0.1-r3[so:libcrypto.so.42]
               libressl2.6-libssl-2.6.3-r0[so:libcrypto.so.42]
  libressl2.6-libssl-2.6.3-r0:
    masked in: @main
    satisfies: wrk-4.0.1-r3[so:libssl.so.44]
```
I would suggest that if you have the image working just update the previous one: `smallnest/go-web-framework-benchmark` so that end users could just run:

    docker run  -v /opt/data:/data smallnest/go-web-framework-benchmark
