### ISSUE TITLE
Macaron incorrect import path

### ISSUE THREAD

**Issue by tgdn** [smallnest/go-web-framework-benchmark#43]
Hello, you removed macaron from your benchmark in [this](https://github.com/smallnest/go-web-framework-benchmark/commit/1071690497099cfe8d41e78a0b355ba3790e13ab) commit.

But the reason it wasn't building was probably because you used the wrong [import path](https://go-macaron.com/docs/intro/getting_started)

In your code you used `github.com/Unknwon/macaron` but in fact it should be `gopkg.in/macaron.v1`.
I'll add a pull request as soon as I can to fix this.

**Comment by smallnest** [comment]
used `gopkg.in/macaron.v1`
