### ISSUE TITLE
马上要go 1.11了, 你还停留在go 1.9版本上, 能不能作一个更新. 主要关心gin和iris的比较! 你对iris怎么看?

### ISSUE THREAD

**Issue by wzwmzm** [smallnest/go-web-framework-benchmark#47]

**Comment by kirillDanshin** [comment]
Just google it. #16 

Anyway, :+1: on updating Go version

**Comment by savsgio** [comment]
Hi @wzwmzm  and @kirillDanshin,
I have just created a PR with updated bechmarks. https://github.com/smallnest/go-web-framework-benchmark/pull/51 :smile:
