### ISSUE TITLE
机器配置可以说详细点嘛

### ISSUE THREAD

**Issue by guonaihong** [smallnest/go-web-framework-benchmark#48]
E5-2630 v3 是8物理核心，16超线程。配置表里说的32 cores是32个物理核还是32个超线程。
其实就想知道用了2块e5还是4块e5。
CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, 32 cores

**Comment by smallnest** [comment]
32超线程，2块

**Comment by guonaihong** [comment]
谢谢。。。
