### ISSUE TITLE
Add kataras/muxie to benchmark

### ISSUE THREAD

**Issue by dumindu** [smallnest/go-web-framework-benchmark#56]
Hi,
Can you add https://github.com/kataras/muxie to benchmark tests?
Thanks

**Comment by smallnest** [comment]
Sure! I will add it into the code.

**Comment by kirillDanshin** [comment]
@smallnest https://github.com/the-benchmarker/web-frameworks/issues/1129

**Comment by dumindu** [comment]
@smallnest @kirillDanshin I don't know what's going on there but why we need to remove `muxie`?
