### ISSUE TITLE
What about echo v4?

### ISSUE THREAD

**Issue by frederikhors** [smallnest/go-web-framework-benchmark#61]
What about echo v4?

**Comment by Fenny** [comment]
@frederikhors, feel free to create a pull request :smile_cat:

**Comment by smallnest** [comment]
upgrade echo to v4

**Comment by frederikhors** [comment]
> upgrade echo to v4

Why did you close this, @smallnest?

**Comment by smallnest** [comment]
because already upgraded to echov4
