### ISSUE TITLE
Question about pipelining test.

### ISSUE THREAD

**Issue by razonyang** [smallnest/go-web-framework-benchmark#76]
Hi, I found that pipelining test is using URL `/` instead of `/hello` for testing, is it correct behavior?

I wrote a simple middleware for verifying this issue:

```go
func Logging(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp := &response{ResponseWriter: w}
		defer func() {
			log.Printf("URI: %s, code: %d", r.RequestURI, resp.code)
		}()
		next.ServeHTTP(resp, r)
	})
}

type response struct {
	http.ResponseWriter
	code int
}

func (r *response) WriteHeader(code int) {
	r.code = code
	r.ResponseWriter.WriteHeader(code)
}
```

And then

```shell
$ go build -o gowebbenchmark

$ ./test.sh
2020/05/05 15:50:26 URI: /hello, code: 0
2020/05/05 15:50:26 URI: /hello, code: 0
2020/05/05 15:50:26 URI: /hello, code: 0
......

$ ./test-pipelining.sh
2020/05/05 15:48:25 URI: /, code: 404
2020/05/05 15:48:25 URI: /, code: 404
2020/05/05 15:48:25 URI: /, code: 404
......
```

https://github.com/smallnest/go-web-framework-benchmark/blob/4eda8a805da3ccdae22c30d45feb389d1de368eb/test-pipelining.sh#L23

BTW, what does `-- / 16` means here? I changed it to `-- /hello 16`, and works as expected.

> `-- / 16` looks like the parameters passed to lua script, / is the request uri and 16 is depth.

**Comment by smallnest** [comment]
great found. fixed and I will do a new benchmark>
