### ISSUE TITLE
http: Accept error: accept tcp [::]:8080: accept4: too many open files

### ISSUE THREAD

**Issue by Karif** [smallnest/go-web-framework-benchmark#97]
Hello,

I made a fresh setup today and started to get these errors. Any idea ?

Host machine is Ubuntu 20.04 with go 1.15.

2020/08/26 14:31:24 - atreugo - Temporary error when accepting new connections: accept tcp4 0.0.0.0:8080: accept4: too many open files
2020/08/26 14:31:25 - atreugo - Temporary error when accepting new connections: accept tcp4 0.0.0.0:8080: accept4: too many open files
2020/08/26 14:31:26 - atreugo - Temporary error when accepting new connections: accept tcp4 0.0.0.0:8080: accept4: too many open files
throughput: 118162.25 requests/second
./test.sh: line 18:  3216 Killed                  ./$server_bin_name $2 $3
finsihed testing atreugo

testing web framework: beego
   • Initialization            package=gramework version=1.7.0-rc3
   • node info                 cputicks=2.53G package=gramework ram=911.18M used / 7.51G total swap=0.00 used / 2.00G total
   • load average is good      fifteen=0.600 five=1.670 one=4.920 package=gramework
   • node uptime               package=gramework uptime= 0:01
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 5ms
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 10ms
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 20ms
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 40ms
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 80ms
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 160ms
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 320ms
2020/08/26 14:31:30 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 640ms
2020/08/26 14:31:31 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 1s
2020/08/26 14:31:32 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 1s

Best Regards,

**Comment by Karif** [comment]
My limits.conf;
root soft nproc 6815744
root hard nproc 6815744
root soft nofile 6815744
root hard nofile 6815744
mysername soft nproc 6815744
myusername hard nproc 6815744
myusername soft nofile 6815744
myusername hard nofile 6815744

**Comment by ntsd** [comment]
I got the same problem but I reduce the concurrency number from 5000 to 2000 and it works.

**Comment by smallnest** [comment]
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_tw_reuse = 1

**Comment by martijnjanssen** [comment]
You can just do `ulimit -n 100000` or something similar to raise the files you can have open.

**Comment by Cypredar** [comment]
I got the same problem and solved it by following https://unix.stackexchange.com/questions/8945/how-can-i-increase-open-files-limit-for-all-processes/8949#8949
